import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
    const bgImageUrl = "/MainBg.jpg";
    return (
        <html lang="en">
            <body className={`${inter.className}`} style={{
          backgroundImage: `url(${bgImageUrl})`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}>{children}</body>
        </html>
    );
}
