import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nutrify Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const bgImageUrl = "/MainBg.jpg";
  return (
    <>
    <html lang="en">
      <body className={`${inter.className}`} style={{
          backgroundImage: `url(${bgImageUrl})`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}>{children}</body>
    </html>
    </>
  );
}
